services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=skyler
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=riri420! #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=skyler.oriordan@mymail.champlain.edu
      - PGADMIN_DEFAULT_PASSWORD=riri420!
    ports:
      - 5050:80
    restart: always
